### ISSUE TITLE
BLOAD SCREEN 5

### ISSUE THREAD

**Issue by sfranck72** [bosh77/MsxCompilerV4#3]
Hello,
I don't find example to load a SCREEN 5 picture with the palette into de file .SC5.
I've made the following code :

1 Dim palette(32) As Byte 
2 Dim I As Byte 

10 Screen 5 : Color 15,0,0
15 Line(0,0)-(255,212),0,BF
20 LoadDataToVram 0,"AWAKE.sc5",0
21 For I=0 To 31
22 palette(I) = Vpeek(30343+I)
23 Next I
28 SetPalette palette

30 Goto 30

The image is on the screen with the good palette color but the image has a shift of several pixels on the right, and glitches (my image is good if I BLOAD in default basic)

![image](https://github.com/bosh77/MsxCompilerV4/assets/12632127/cb53df59-ec69-462c-aa23-0ec961432061)
[AWAKE.zip](https://github.com/bosh77/MsxCompilerV4/files/14215640/AWAKE.zip)

**Comment by bosh77** [comment]
Hello,

The "LoaddataTovram" command is a little different from "Bload", because it
loads the entire content of the file without considering the header.
It is necessary to remove the first 7 bytes from the "*.sc5" file,
otherwise you have to upload the file with an offset of -7 or 65529 and set
"setpage 0.2" and also change the address of the colors of the palette
(30336 instead of 30343)

Try this:

1 Dim palette(32) As Byte
2 Dim I As Byte

10 Screen 5 : Color 15,0,0
15 Line(0,0)-(255,212),0,BF
16 SetPage 0,2
20 LoadDataToVram 0,"lesson.sc5",65529
21 SetPage 0,0
22 For I=0 To 31
23 palette(I) = Vpeek(30336+I)
24 Next I
28 SetPalette palette

30 Goto 30













Il giorno ven 9 feb 2024 alle ore 00:26 sfranck72 ***@***.***>
ha scritto:

**Comment by sfranck72** [comment]
It works ! 
I suspected it was the header because of the offset of the color table but I couldn't get around it in the display function.
Thank you for the feedback.
Great tools that deserve more simple examples of this type to promote it.
Crazy job anyway.

**Comment by bosh77** [comment]
Thank you! I think I could add Bload and Bsave instructions, and other
useful functions for managing files

Il Ven 9 Feb 2024, 15:28 sfranck72 ***@***.***> ha scritto:
